<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;
use Neoan3\Apps\Session;

class Header extends Unicore {
    function __construct() {
        new Session();
        if(!isset($_SESSION['language'])) {
            Session::add_session(
                [
                    'language' => 'english',
                ]
            );
        }
        if(!isset($_SESSION['gender'])) {
            Session::add_session(
                [
                    'gender' => 'female',
                ]
            );
        }
    }

    function postHeader($obj){
        $_SESSION['language'] = $obj['language'];
        $_SESSION['gender'] = $obj['gender'];
    }
}
