<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;
use Neoan3\Frame\Demo;
use SleekDB\SleekDB;

class Languages extends Unicore {
    private $store;
    function __construct() {
        $this->store = SleekDB::store('languages',path.'/asset/db');
    }

    function getLanguages(){
        return $this->store->fetch();
    }

    function postLanguages($obj){
        if(isset($obj['languageId'])){
            $update = $this->store->where('_id','=',$obj['languageId'])->fetch();
            $update[0]['accents'][] = ['name'=>$obj['name']];

            $this->store->where('_id','=',$obj['languageId'])->update(['accents'=>$update[0]['accents']]);
        } else {
            $this->store->insert(['name'=>$obj['name'],'accents'=>[]]);
        }

        return $this->getLanguages();
    }
    function deleteLanguages($obj){
        if($obj['type'] == 'accent'){
            $language = $this->store->where('_id','=',$obj['_id'])->fetch()[0];
            $accents = [];
            foreach($language['accents'] as $i=>$accent){
                if($i !== $obj['accent']){
                    $accents[] = $accent;
                }
            }
            $this->store->where('_id','=',$obj['_id'])->update(['accents'=>$accents]);
        }
        return $this->getLanguages();
    }

}
