<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Session;
use Neoan3\Core\Unicore;
use Neoan3\Frame\Demo;

class Logout extends Unicore {
    function __construct() {
        new Session();
        ini_set('display_errors',false);
    }

    function init(){
        $this->getLogout();
        $this->uni('demo')->callback($this,'getLogout')->callback($this,'view')->output();
    }
    function getLogout(){
        try{
            Session::logout();
        } catch(\Exception $e){
            // ignore
        }
    }

    /**
     * @param \Neoan3\Core\Serve $uni
     */
    function view($uni){
        $uni->addHead('meta',['http-equiv'=>'refresh','content'=>'4;url='.base]);
        echo 'You are logged out';
    }


}
