<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Session;
use Neoan3\Core\Unicore;
use SleekDB\SleekDB;
use Neoan3\Frame\Demo;

class NeoanAccents extends Unicore {
    private $store;
    function __construct() {
        new Session();
        $this->store = SleekDB::store('languages',path.'/asset/db');
    }
    function getNeoanAccents($obj){
        $language = $this->store->where('name','=',$obj['language'])->fetch();
        if(!isset($_SESSION['accents'])) {
            Session::add_session(['accents'=>$language[0]['accents']]);
        }

        return ['all'=>$language[0]['accents'],'chosen'=>$_SESSION['accents']];
    }
}
