<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Ops;
use Neoan3\Core\Unicore;
use Neoan3\Frame\Demo;
use SleekDB\SleekDB;

class Profile extends Unicore {
    function postProfile($obj){

        $clean = Ops::extrude(['language','type','picture','name','gender','fileLocation'],$obj);
        $clean['accents'] = [];
        foreach($obj['spokenAccents'] as $spokenAccent){
            $clean['accents'][] = ['name'=>$spokenAccent['name']];
        }
        $storeName = $obj['type'];
        $store = SleekDB::store($storeName,path.'/asset/db');
        if(!isset($obj['_id'])){
            return $store->insert($clean);
        } else {
            $store->where('_id','=',$obj['_id'])->update($clean);
            $clean['_id'] = $obj['_id'];
            return $clean;
        }
    }
    function deleteProfile($obj){
        $store = SleekDB::store($obj['type'],path.'/asset/db');
        $store->where('_id','=',$obj['_id'])->delete();
    }
}
