<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Session;
use Neoan3\Core\Unicore;

class Admin extends Unicore {

    function restrict(){
        if(!Session::is_logged_in()) {
            redirect('login');
            exit();
        }
    }
    function init() {

        $this->uni('demo')->callback($this,'restrict')
             ->includeElement('admin')
             ->includeElement('admin-settings')
             ->includeElement('services')
             ->includeElement('profile-list')
             ->includeElement('profile')
             ->hook('main', 'admin')
             ->output();
    }

}
